### ISSUE TITLE
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req (-1)

### ISSUE THREAD

**Issue by yo0x** [SkypLabs/probequest#37]
when running it on my raspberry i get this error:
`!
pi@raspberrypi:~/Probe-Hunter $ sudo probequest -i wlan0
[*] Start sniffing probe requests...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 907, in _run
    *arg, **karg)] = iface
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 407, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 142, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/common.py", line 129, in compile_filter
    "Failed to compile filter expression %s (%s)" % (filter_exp, ret)
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req (-1)

[*] Stopping the threads...
^C[*] Bye!
`

i tried to reinstall tcpdump as suggested on the web, but it wont work.

**Comment by SkypLabs** [comment]
Hi @yo0x,

Is your interface in monitor mode as explained in the documentation?

Also, for the next time, please follow the bug report template because you didn't give details about your execution environment (version of ProbeQuest, OS, etc.).

**Comment by yo0x** [comment]
it was. made a fresh install and everything works just fine!

OS: Raspberry Pi OS Lite, Probequest 0.7.2

**Comment by ludflahs** [comment]
Hey, i'm having a same issue! Monitor mode enabled and version is Probequest 0.7.2.

airmon-ng start wlan0


PHY     Interface       Driver          Chipset

phy0    wlan0           mt7601u         Edimax Technology Co., Ltd Edimax Wi-Fi
                (monitor mode enabled)

                                                                           
┌──(root💀kali)-[/home/kali]
└─# probequest -i wlan0
[*] Start sniffing probe requests...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 906, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 407, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 142, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/common.py", line 128, in compile_filter
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req (-1)
^C[*] Stopping the threads...
^CTraceback (most recent call last):
  File "/usr/local/bin/probequest", line 118, in main
    sleep(100)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/probequest", line 149, in <module>
    main()
  File "/usr/local/bin/probequest", line 128, in main
    raw_viewer.stop()
  File "/usr/local/lib/python3.8/dist-packages/probequest/ui/raw.py", line 54, in stop
    self.sniffer.stop()
  File "/usr/local/lib/python3.8/dist-packages/probequest/probe_request_sniffer.py", line 65, in stop
    self.parser.join()
  File "/usr/local/lib/python3.8/dist-packages/probequest/probe_request_parser.py", line 71, in join
    super().join(timeout)
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^C
