### ISSUE TITLE
libpcap0.8 version 1.10 breaks the application

### ISSUE THREAD

**Issue by warp123** [SkypLabs/probequest#39]
Installed on Kali machine. After fresh kali installations the program works just fine, but after a full-upgrade of the OS, probequest stops working with the following error 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 906, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 407, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 142, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/lib/python3/dist-packages/scapy/arch/common.py", line 128, in compile_filter
    raise Scapy_Exception(
scapy.error.Scapy_Exception: Failed to compile filter expression type mgt subtype probe-req (-1)

I had similar problems with bettercap when the program was trying to set the wifi adapter in monitor mode, and the problem was there with the library "libpcap0.80" which is updated in version 1.10 lately. 

We tried installing the previous version 1.9.1 and both applications now work perfectly.

I am also addressing the issue here, in order to help anybody else experiencing the same problems.

**Comment by green-butterfly** [comment]
Hey.
Same issue on my Kali machine as well.
Last OS upgrade: 2 days ago.

**Comment by warp123** [comment]
Downgrade the libpcap version to 1.9.1 and it will work again. I personally marked the package not to be upgraded by apt until it gets fixed.

**Comment by green-butterfly** [comment]
Ok.
Thanks :)

**Comment by ludflahs** [comment]
Hey guys how you downgrade the libpcap version? Where i can find that documentation for do it? i tryed install libpcap0.8=1.9.1, but says it didnt find the version for it. Where i can bypass this? I'm really getting mad because i'm 2 hours finding and testing everything to solve this and nothing works. Help me guys please

**Comment by warp123** [comment]
wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb
dpkg -i libpcap0.8_1.9.1-4_amd64.deb

**Comment by ludflahs** [comment]
> wget http://old.kali.org/kali/pool/main/libp/libpcap/libpcap0.8_1.9.1-4_amd64.deb
> dpkg -i libpcap0.8_1.9.1-4_amd64.deb

Thank you so much men!!!

Now when i run with root( needed ) it says he didnt find the module, what ?!


┌──(kali㉿kali)-[~]
└─$ probequest
usage: probequest [-h] [--debug] [--fake] -i INTERFACE [--ignore-case]
                  [--mode {raw,pnl}] [-o OUTPUT_FILE] [--version]
                  [-e ESSID_FILTERS [ESSID_FILTERS ...] | -r ESSID_REGEX]
                  [--exclude MAC_EXCLUSIONS [MAC_EXCLUSIONS ...] | -s
                  MAC_FILTERS [MAC_FILTERS ...]]
probequest: error: the following arguments are required: -i/--interface
                                                                           
┌──(kali㉿kali)-[~]
└─$ sudo probequest                                                    2 ⨯
[sudo] password for kali: 
Traceback (most recent call last):
  File "/usr/local/bin/probequest", line 13, in <module>
    from probequest.config import Config, Mode
ModuleNotFoundError: No module named 'probequest'

**Comment by warp123** [comment]
Are you sure that you provided the right syntax? 
Sudo probequest -i wlan0mon

Presumably that you have set the wlan0 interface to monitor mode

**Comment by ludflahs** [comment]
Yep i provided right syntaxt but i can do it to show better:


![issue](https://user-images.githubusercontent.com/78989528/107862018-b1cf1400-6e41-11eb-9f99-264e94a4bf41.png)

**Comment by warp123** [comment]
Nope. Your syntax is not right. After you start airmon-ng on wlan0 then interface is named wlan0mon. Check it with a simple ifconfig. So the right syntax is as I wrote to you earlier
Sudo probequest -i wlan0mon

**Comment by ludflahs** [comment]
> Nope. Your syntax is not right. After you start airmon-ng on wlan0 then interface is named wlan0mon. Check it with a simple ifconfig. So the right syntax is as I wrote to you earlier
> Sudo probequest -i wlan0mon

My monitor mode is different, gives a wlan0 to use on monitor mode. But thanks i make it work, i reinstall kali linux and tryed again and voilá it worked ;) so happy. Anyway thank you so much to downgrade libpcap!
![worked](https://user-images.githubusercontent.com/78989528/107863031-eb574d80-6e48-11eb-89e1-a24a4da224f7.png)

**Comment by dave7280** [comment]
Same problem here. Kali 2021.1.
Downgrading libpcap does not help.

**Comment by SkypLabs** [comment]
The issue seems to have been fixed upstream a while ago: https://github.com/the-tcpdump-group/libpcap/issues/989
