### ISSUE TITLE
Error when trying to decode ESSIDs using invalid UTF-8 characters

### ISSUE THREAD

**Issue by SkypLabs** [SkypLabs/probequest#4]
An exception is raised when an ESSID contains invalid UTF-8 characters:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/bin/sniff-probe-req", line 239, in run
    probe_request = self.parse(packet)
  File "/usr/local/bin/sniff-probe-req", line 273, in parse
    essid = packet.getlayer(Dot11ProbeReq).info.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 1: invalid start byte
```

**Comment by SkypLabs** [comment]
This issue has been fixed and will be included in the next release.

**Comment by SkypLabs** [comment]
Version 0.7.1 contains a patch addressing this issue.
